# Site settingsa
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jerry Miguel Torres Guzmán"
resume_title:                   "Experimental sciences pedagogy Computer science"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jerry.torres@unach.edu.ec"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+593 ** *** ****"
resume_contact_address:         "Campus Dolorosa in Riobamba,Ecuador"

resume_header_contact_info:     ""false"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hello, I am Jerry Torres, I'm 21 years old, I consider myself a person with many virtues, skills, abilities and defects that characterize me as a person among which I could highlight is that I am friendly, sociable, cheerful, respectful among others, my defects that usually is that I am a perfectionist and I like to work alone, however I am always willing to listen to suggestions and to accept my mistakes and learn from them since it is our mistakes that make us human, while my skills, abilities and skills I will continue to tell you later.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://jerry50r8.github.io/"
  resume_twitter_url:           "https://twitter.com/JerryTo10726616"
  # resume_dribbble_url:          ""
  resume_facebook_url:          "https://www.facebook.com/jerry.torres.583"
  resume_linkedin_url:          "https://www.linkedin.com/in/jerry-torres-b438a1198/"
  resume_instagram_url:         "https://www.instagram.com/jerry_50r8/"
  resume_website_url:           "https://www.youtube.com/channel/UCfhN2jxfJXro2OjdvSFIE2Q"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
